# Generated by Django 4.2.3 on 2023-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0004_alter_invoicedetail_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
